name: ✨ Feature request
description: Request a new feature.
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        - Avoid generic or vague titles such as "Something's not working" or "A couple of problems" — be as descriptive as possible.
        - Keep your issue focused on one single problem. If you have multiple feature requests, please create a separate issue for each of them.
        - Issues should represent **complete and actionable** work items. If you are unsure about something or have a question, please start a [discussion](https://github.com/Tyrrrz/CliWrap/discussions/new) instead.
        - Remember that **CliWrap** is an open-source project funded by the community. If you find it useful, **please consider [donating](https://tyrrrz.me/donate) to support its development**.

        ___

  - type: textarea
    attributes:
      label: Details
      description: Clear and thorough explanation of the feature you have in mind.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      description: Quick list of checks to ensure that everything is in order.
      options:
        - label: I have looked through existing issues to make sure that this feature has not been requested before
          required: true
        - label: I have provided a descriptive title for this issue
          required: true
        - label: I am aware that even valid feature requests may be rejected if they do not align with the project's goals
          required: true
        - label: I have sponsored this project
          required: false
